spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=testcontainer&password=postgres&user=postgres
    platform: postgres

  jpa:
    generate-ddl: 'false'
    show-sql: 'false'
    hibernate:
      ddl-auto: validate